# Generated by Django 3.2.4 on 2021-06-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_index', '0003_auto_20200724_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='appgroup',
            name='icon',
            field=models.FileField(blank=True, upload_to='', verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='applink',
            name='icon',
            field=models.FileField(blank=True, upload_to='', verbose_name='icon'),
        ),
    ]
