# Generated by Django 3.2.4 on 2021-06-11 02:26

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_index', '0005_auto_20210611_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Theme name')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('dm_bc', colorfield.fields.ColorField(default='#417690', max_length=18, verbose_name='.dropdown-menu background color')),
                ('dm_hover_bc', colorfield.fields.ColorField(default='#79aec8', max_length=18, verbose_name='.dropdown-menu:hover background color')),
                ('dm_i_c', colorfield.fields.ColorField(default='#fff', max_length=18, verbose_name='.dropdown-menu item color')),
                ('dm_drop_bc', colorfield.fields.ColorField(default='#417690', max_length=18, verbose_name='.dropdown-menu__drop:hover background color')),
                ('dm_drop_hover_bc', colorfield.fields.ColorField(default='#79aec8', max_length=18, verbose_name='.dropdown-menu__drop background color')),
                ('dm_drop_c', colorfield.fields.ColorField(default='#fff', max_length=18, verbose_name='.dropdown-menu__drop color')),
            ],
            options={
                'verbose_name': 'design theme',
                'verbose_name_plural': 'design themes',
            },
        ),
    ]
