# Generated by Django 3.2.4 on 2021-06-11 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_index', '0006_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='dm_i_c',
            new_name='dm_c',
        ),
    ]
